### ISSUE TITLE
Weird rendering error, might be fault of Scatter or EVE

### ISSUE THREAD

**Issue by MandelbrotEnjoyer** [KSP-RO/RSS-CanaveralHD#5]
Not really sure why it's happening, maybe fault of Scatter or Eve but just putting it out here. Only Canaveral is rendered properly when in atmosphere.

KSP 1.10.1.2939

![KSP_BUG_REPORT](https://github.com/KSP-RO/RSS-CanaveralHD/assets/144078648/3976106d-2969-4cf1-87fc-925fcc91fe90)
[Mod_List_For_Bug_Report.txt](https://github.com/user-attachments/files/16030349/Mod_List_For_Bug_Report.txt)

**Comment by siimav** [comment]
The terrain decal added by this mod is rendering perfectly. Can't say the same about your planet textures though.

**Comment by MandelbrotEnjoyer** [comment]
Turned out it was caused by Parallax mod, after uninstalling it everything is fine
